### ISSUE TITLE
Ashsiinha@gmail.com

### ISSUE THREAD

**Issue by sumitsinhaa** [SubhamTyagi/loco-answers#100]
Bro mera naam Sumit hai Yeh To Kehne ki jarurat nahi hai ki aap sabse best developer Ho and ek request aur hai Ek app aur hai Jisko aap uske andar add kar sakte ho ( Q Live ) trivia game pound main paise provide karti hai please help @SubhamTyagi

**Comment by sumitsinhaa** [comment]
Bro mera naam Sumit hai Yeh To Kehne ki jarurat nahi hai ki aap sabse best developer Ho and ek request aur hai Ek app aur hai Jisko aap uske andar add kar sakte ho ( Q Live ) trivia game pound main paise provide karti hai please help @SubhamTyagi

**Comment by sumitsinhaa** [comment]
Bro mera naam Sumit hai Yeh To Kehne ki jarurat nahi hai ki aap sabse best developer Ho and ek request aur hai Ek app aur hai Jisko aap uske andar add kar sakte ho ( Q Live ) trivia game pound main paise provide karti hai please help @SubhamTyagi

**Comment by SubhamTyagi** [comment]
Okay i will try for Q live
