### ISSUE TITLE
Loco letest version not working

### ISSUE THREAD

**Issue by gupta0708** [SubhamTyagi/loco-answers#103]
Subham  tyagi 
bro loco letest version 1.7.5 not work in jio network and brain baazi game

**Comment by vikram9494** [comment]
Am using old version only bro loco 1.9.0.
it is not working with data working with wifi bro ...
What is the solution for this....

**Comment by selenamariogomez** [comment]
Use VPN...   and check test mode working or not...  after go to play the game

**Comment by vikram9494** [comment]
VPN MEANS BRO

**Comment by zamizayn** [comment]
Try turbo vpn

**Comment by gupta0708** [comment]
https://gg-l.xyz/hdBgzMVl5u
Download this application and use loco  hack
But only qureca and swoo trivia game show
