### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by zamizayn** [SubhamTyagi/loco-answers#104]
Everything is good , but now a days it's showing wrong answer for the last question

**Comment by selenamariogomez** [comment]
Yes..please fix this. 9 question answer was correct but final one wrong.

**Comment by zamizayn** [comment]
Yes the same issue , when I played swoo just moments ago , three out of five questions were wrong

**Comment by zamizayn** [comment]
@selena does using a lower version of loco hack will work???

**Comment by selenamariogomez** [comment]
Dont know... try it

**Comment by selenamariogomez** [comment]
Do you use weshow app ?????

**Comment by zamizayn** [comment]
please note that during the quiz , if any of the answer comes with a count of 24 , it will be the correct one

**Comment by gupta0708** [comment]
Loco letest vision work hq trivia game show????

**Comment by zamizayn** [comment]
@gupta0708 Yess , and I have earned 4 dollars past week
