### ISSUE TITLE
Problem with the search occurrence

### ISSUE THREAD

**Issue by chanx74** [SubhamTyagi/loco-answers#106]
Question is from 8:30 pm on 21 Aug on quereka 
Who among these was the first to win an international beauty pageant title? 

Option 1. Srishti rana

Option 2. Dia mirza

Option 3. Yukta mookhey 

Instead of just counting for "dia"  python is considering the word "india" 

India = in + dia  (ignore "in") and count dia

Then dia will come a kabillion times

Due to this every idiot fell for option 2

The answer was option 3 yukta mookhey 

Simple fix is to put a function that will 

A) not trim the chars that preceed and succeed the options 

B) put a dictionary filter of the most confused proper nouns 

Ex:- 'dia'  mirza and in'dia'; 'shah'rukh and 'shah'id kapoor etc....

**Comment by selenamariogomez** [comment]
Please fix this.. i choose 2nd option, I lost the game..

**Comment by ronymandal** [comment]
Yaaa plz fix🙏

**Comment by SubhamTyagi** [comment]
Is talking about loko hack?

**Comment by ronymandal** [comment]
Yes

**Comment by SubhamTyagi** [comment]
@chanx74 @ronymandal 
Yeah i checked out this bug in next version it will be fixed.
you can check implementation of this [here](https://gist.github.com/SubhamTyagi/28afed0715271fe2fbbb5a171bccbde3) 

thanks.
