### ISSUE TITLE
Loko hack is not working on brain baazi Mi Phones only

### ISSUE THREAD

**Issue by ashok-bansal** [SubhamTyagi/loco-answers#107]
Loko Hack is really a very good app for qureka and swoo. But it does work on mi phones for brainbazi app. Pls solve.

**Comment by hackthon2018** [comment]
Yaa

**Comment by selenamariogomez** [comment]
Swoo version ???

**Comment by hackthon2018** [comment]
Loko hack also not working for me
From last day it's not working for me what about u ?

**Comment by selenamariogomez** [comment]
Use vpn

**Comment by hackthon2018** [comment]
Which vpn ur using

**Comment by selenamariogomez** [comment]
Use any. Im using zero vpn..

**Comment by selenamariogomez** [comment]
Which sim you using ? Jio ??

**Comment by hackthon2018** [comment]
Even though I am using vpn it's not showing answers at certain time
For example giving answers till 4 thereafter not showing

**Comment by selenamariogomez** [comment]
Force to stop the app. And clear data & cache...

**Comment by selenamariogomez** [comment]
Do in Loko app
