### ISSUE TITLE
Someone Help!!!!!

### ISSUE THREAD

**Issue by meuserhere** [SubhamTyagi/loco-answers#110]
I have installed it in my two mobiles, both worked well. But now from yesterday its not working at all in both the phones. What's wrong with it. Whenever i tap on Get Answer, it keep searching but dont show any result

**Comment by selenamariogomez** [comment]
Clear data for loko hack..  and try vpn app...   do you use baazi app ??

**Comment by meuserhere** [comment]
yes, it works with VPN. But most of the time it is giving wrong answer even in very easy question

**Comment by selenamariogomez** [comment]
If question is easy dont use loko option

**Comment by Saurabh2548** [comment]
Which vpn is used give me some app name which is very fastest or another
thing plz tell me version of brain baz i

**Comment by selenamariogomez** [comment]
Im using zero vpn app.   1st clear data for loko app.

**Comment by SahilBagdi** [comment]
will it work in loco and bazzinow if then how

**Comment by meuserhere** [comment]
no, for me it doesn't work on Loco, Brainbaazi or Weshow. It can be used for Qureka, HQ and Swoo.

**Comment by meuserhere** [comment]
@Saurabh, VPN app maybe what, but comparatively it always slower than without VPN like i used earlier. I tried with 2/3 VPN apps and now i am using Thunder VPN
