### ISSUE TITLE
Couldn't get too work with hq

### ISSUE THREAD

**Issue by stdded** [SubhamTyagi/loco-answers#115]
Have zero vpn still didn't work. Do I run hq and loko through the vpn? Help please.

**Comment by ronymandal** [comment]
Yes it works with vpn

**Comment by stdded** [comment]
It won't answer I just keep getting errors

**Comment by selenamariogomez** [comment]
Force stop the loko app and clear data..    try again with vpn... try test
mode work? Or not ?

**Comment by NEMS1996** [comment]
Update is not working properly ....the options are  not being displayed after clicking get answer .......Please check and fix it

**Comment by stdded** [comment]
@selena text mode was working but im having the same problem as nems.
