### ISSUE TITLE
Loko 1.7.6

### ISSUE THREAD

**Issue by hackthon2018** [SubhamTyagi/loco-answers#116]
Is this version works without any VPN or not ?

**Comment by ronymandal** [comment]
It works and give answers without vpn but sometime it refreshes the answer so that question get wrong, this is the main problem in this version

**Comment by hackthon2018** [comment]
Is it working on new versions of the app only or older versions also

**Comment by ronymandal** [comment]
I dont try this now

**Comment by hackthon2018** [comment]
What Loko new version? Or the apps versions

**Comment by Pratik02chauhan** [comment]
How to download this app?? Not able to download

**Comment by deviladitya** [comment]
Not work with jio internet please solve it

**Comment by saitejashree** [comment]
Every version are not working now...what is the prblm of the..
