### ISSUE TITLE
Regarding loko hack 

### ISSUE THREAD

**Issue by Saurabh2548** [SubhamTyagi/loco-answers#12]
Sir Loko hack new version  is not working in any app game Trivia show what I'm doing plz tell me and plz solve all problems of loko hack

**Comment by harshvhgzdd** [comment]
Yes not working

**Comment by Saurabh2548** [comment]
Plz

**Comment by harshvhgzdd** [comment]
Plz means

**Comment by Saurabh2548** [comment]
Koi jaldi loko ka Version nikaliye jo kam kare

**Comment by SubhamTyagi** [comment]
update it

**Comment by Saurabh2548** [comment]
Ok

**Comment by pankaj19841984** [comment]
sir loco ka old virsion jab v loko app use karta hu to hang kar jata hai. iska kuch solusion bataiy???plss
sir , isme outo answer ka koi optin lane se accha hota.

**Comment by teamkolayat123** [comment]
Bro loco hack is not working in normal mode it always shows finding answer  in loco swoo etc .What is the reason I have updated it when update is available but not working bro
