### ISSUE TITLE
now searching answers in loko hack 1.7.6

### ISSUE THREAD

**Issue by 3D-GaminG** [SubhamTyagi/loco-answers#120]
hi i downloaded loko hack latest version and used it the 1st day without any problem but the next day i simply wouldn't search the answers i had to manually deny the permission and accept it again for it too work but even that was temporary. the app doesnt even search the test question the app.
please help
i am using redmi 4 btw
thanks

**Comment by selenamariogomez** [comment]
Bro use VPN app....

**Comment by saitejashree** [comment]
sir,it is shwng wrong answers....will u pls rectify this problem...

**Comment by shoooka** [comment]
How i can download last version please
