### ISSUE TITLE
Loco 1.9.0 application not installed

### ISSUE THREAD

**Issue by ronymandal** [SubhamTyagi/loco-answers#121]
Is anyone face prblm regarding loco 1.9.0 application now it show update ur app(at present previous version of loco application not installed so how we use loko hack becoz in new version of loco application loko hack doesn't support☹️☹️)

**Comment by selenamariogomez** [comment]
Bro do you have loco 1.9.0 ???

**Comment by selenamariogomez** [comment]
Send link plz

**Comment by ronymandal** [comment]
Yes but it is not supported

**Comment by ronymandal** [comment]
I dont know what the issue it says to update ur app

**Comment by ronymandal** [comment]
Before i use this but works properly but from now it doesn't work

**Comment by Kuldeep657** [comment]
Please sor koi solution nikalo, loko hack letest version me work kare "Loco App" me 
Old version 1.9.0 work nhi kr rha h😭😭

**Comment by vikram9494** [comment]
Yes loco old versions are not installing only latest version opening please solve this issue as soon as possible broo without solution  then our loco hack app is useless broo.
