### ISSUE TITLE
SUGGESTION  FOR LOKO HACK

### ISSUE THREAD

**Issue by SubhamTyagi** [SubhamTyagi/loco-answers#123]
I am currently implementing new feature(ocr) for this app (work is almost complete) i want some suggestion for this:
* There are two way for defining the Question Region one is when live game and other is before game using previously stored screenshot.

suggest me which method i roll out for loko hack or

 if you have another method then suggest

**Comment by saitejashree** [comment]
Implement it live game nly...

**Comment by selenamariogomez** [comment]
Yes live game

**Comment by Kuldeep657** [comment]
Live game bala chahiye sir , loco me kaam to karega na sir🤔🤔

**Comment by Kuldeep657** [comment]
Live game me Answer dene bala sir

**Comment by Anandrulz001** [comment]
Live game would be better, easier to understand for people, i hope it works on updated version of loco coz they have now completely blocked v1.9.0 and can't register even using disabling the internet trick

**Comment by Anandrulz001** [comment]
Suggestions
- if it could search results from flipkart, amazon, dood bazaar and grofers, etc it would be really a helpful in loco bazaar
- loco hack gives many wrong answers for number problems so if something could be done in that regard... 
Thank you. 
Kkeep your gr8 work

**Comment by vikram9494** [comment]
Yes live game and loco1.9.0 & old versions not installing keep fix with latest version loco app otherwise it is waste Bro..

**Comment by mackesh** [comment]
First thanks to u sir for this brilliant job...
Sir second one... Because our LH working on specific trivia games.. 
So stored screenshot method should be best....

**Comment by SahilBagdi** [comment]
Screenshot because screenshot will work in every trivia but live will not
work in some of trivia


On Sep 15, 2018 8:50 PM, "rana4209211" <notifications@github.com> wrote:

screenshot method should be best

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/SubhamTyagi/loco-answers/issues/123#issuecomment-421585999>,
or mute the thread

**Comment by vikram9494** [comment]
Sir 2.1.9 loco remove add latest versions to work our app because old versions are gone cn't register now so......relz some new trick to loco hack

**Comment by devmji** [comment]
sir previously stored screenshot will be better option,no need to set it everytime we play a game.

**Comment by srbsppatil** [comment]
Release both

**Comment by Kuldeep657** [comment]
Sir to screenshot method hi badiya hai to jaldi se new update do sir😊😊

**Comment by sngvs** [comment]
Old loco versions like 1.9.0, 2.1.3 all are fully disabled and loko hack not working Plz provide new update for loco which work on latest loco version

**Comment by deviladitya** [comment]
Sir please made answer for Loco Trivia.

**Comment by Kuldeep657** [comment]
Sir kb Update karoge app hum wait kar rhe hai next update ka ..........

**Comment by patnaiksubrat** [comment]
now older version loco totally unsupported and not able to register in. give any other option for loco

**Comment by mackesh** [comment]
Sir...
Where r u....? 
where  ur releases?
Do something great... We r all waiting..
,😊😊😊

**Comment by vikram9494** [comment]
Sir update new release fast bhayya we are waiting...
Any body getting loco hack old links to download im not getting any links 
Why it is only for me or others alsoo

**Comment by vikram9494** [comment]
Helll sir...
Why loco hack all versions are deleted
Coming with any new solution ?
Sir please do one commit here about coming or not
These page continuos or stoped..........

**Comment by Kuldeep657** [comment]
Sir new update kb doge ye bata do please

**Comment by Kuldeep657** [comment]
Aur old version saare delete kyu kar diye please answer do.....

**Comment by Kuldeep657** [comment]
Thanks sir batane ke liye kb se pareshan tha........you are great

**Comment by vikram9494** [comment]
Thank you soooo much sir  your reacted to my  request.......
We are waiting to new updates am hoping it is better than before solution

**Comment by deviladitya** [comment]
I appreciate your work.
Thanks brother I'm waiting for your update.

**Comment by patnaiksubrat** [comment]
thanks Subham for your contribution..
