### ISSUE TITLE
Suggestion to add hindi language in search

### ISSUE THREAD

**Issue by gylRghv** [SubhamTyagi/loco-answers#126]
Brother so far you have done a fab job and I have donated some money for your work ...keep it up!!
Can you also add hindi language games for loko hack to work upon ...
Actually it would be pretty cool to let us choose where  question is and where the options are displayed.
*Add hindi please*

**Comment by Kuldeep657** [comment]
Bhai english hi achhi hai kyuki ek problem hai jb questions enlish me aayega to hum logo ko answer app sahi ans. dega aur agar hindi me aata hai to kuchh ans. hi thik milege mai check kr chuka hu, hindi me ans. km iss wajah se milte hai kyuki koi questions tum search karke dekhna google pe to hindi me uska ans. bahut hi km hoga aur agar vahi questions English me karoge to bahut saare result milege iss wajah se ans. app answer de deta hai aur agar hindi hogi to kuchh question bta dega jo search kar lega aur jo hoga hi nhi to usko kese batayega iss wajah se "English" Language hi thik hai bhai abhi best Ans. De deta hai karib 9 questions ke ans. deta hai correct aur kya chahiye bhai ......

**Comment by gylRghv** [comment]
It's true par ocr me screenshot ke lie hindi as an option rakna koi burai nahi hai ...I'm not saying ki tum galat kha rhe ho par ek game hai **playprimetime** , Usme hindi me game ata hai islie bola

**Comment by Kuldeep657** [comment]
Ok bhai koi baat nhi.....

**Comment by SubhamTyagi** [comment]
@gylRghv if you use Hindi in your app accuracy will be decrease due to search engine result limitation. Hindi ocr option will be available in tesseract oce
