### ISSUE TITLE
Hiiii Subham 

### ISSUE THREAD

**Issue by aaryantt** [SubhamTyagi/loco-answers#139]
Hiiii Subham me Technical Teaser se hu aapka purana no. Ek new person ne Liya h jisshe vo bohot pareshan ho gya aapse vo contact karna chahta hai agar ho sake to apna contact no. Ushe de Dena agar aapko usshe contact karna hai to Apne old no. PR baat ke lena

**Comment by SubhamTyagi** [comment]
I have contact that guy. I told him whole matter. He only said that nobody would contact him.



I urge you don't contact that person.

**Comment by aaryantt** [comment]
Ok done

**Comment by raman05007** [comment]
@SubhamTyagi 
Hello **SHubham**  I am Raman from YT channel *HOBO*  *tech*  *hindi*  mai apse Bhot Insparing feel krta hu or  ye khna chahta hu ki apne jo Kiya hai wo kisi or k bas ki bat nhi hai or wo bhi Sabke liye Free Of Cost. I meam Yu are the Best.. lakin apko is Innovation k liye kuchh to milna Chahiye  lakin log sirf apko naam se jante hai wo apne is hero ko dekhna chahenge...
