### ISSUE TITLE
Loko hack 2.0 apk missing

### ISSUE THREAD

**Issue by dee9205** [SubhamTyagi/loco-answers#142]
Hii...where is the apk ..? can we update old version by using the given zip files by you ..!

**Comment by dee9205** [comment]
In assests two files are available..

**Comment by dee9205** [comment]
In assets two zip files are available. One is .zip file and another is .tar
file . And has you released the app?? I cant found apk .plz tell if you
have not released apk i will wait .

**Comment by dee9205** [comment]
Apk is missing ? Why bro .

**Comment by dee9205** [comment]
Thanku bro thanku so much ..i found it.. thanks ...😊😊😊😊😊

**Comment by dee9205** [comment]
Thanks brother..

**Comment by koneruvinodh** [comment]
Where's the APK file
