### ISSUE TITLE
SUGGESTIONS FOR LOKO HACK 2.0

### ISSUE THREAD

**Issue by SubhamTyagi** [SubhamTyagi/loco-answers#158]
Tell me about Loko hack 2.0(OCR speed , features,etc)

Every suggestions is appreciated. If you find any bug feel free to create a issue.

In current beta version a have added a crash reporter if you encounter any crash. Just use that it will automatically adds a relevant info and create a issue on this page.

**Comment by ronymandal** [comment]
Sir loco hack 2.0 not giving answer, i will check in test option it will show blank

**Comment by jahir90** [comment]
Great job. No word to thank u.
This time it is not crashing. But one problem is there. When questions is 2 pr 3 line in brainbaazi kalnayak or runners up sawal it only takes the question line to make the answer option. Original option for answer is not taken by loko hack then

**Comment by SubhamTyagi** [comment]
@jahir90 send a screenshot so i can identify problem.

**Comment by Rishav-G** [comment]
I think i know the problem @jahir90 is referring to.
But to where should i send the screenshot??

**Comment by mackesh** [comment]
Sir make question and options separate cropping.... Because our app can't distinguish question and answer part in Oct mode....

**Comment by pankajksu** [comment]
ocr work kar raha hai. but qustion ko hi 3 option mye dividet karke dikha raha hai, or assibility me v option flactuet kar raha hai , option 2 dikhake 3 kar diya, plss cheku this. thank u , great job subham vai.

**Comment by jahir90** [comment]
Here is the screenshot in the attached file

**Comment by SubhamTyagi** [comment]
I think you could not understand how to crop the question and options area

**Comment by jahir90** [comment]
Sir, I have sent the screenshot to your email

**Comment by SubhamTyagi** [comment]
Crop whole text area where questions and options reside.

I checked it so many time. It is working well. If you are getting any error send me a screenshot, or logs. I will provide a solution and bug free Loko Hack.

**Comment by Rishav-G** [comment]
Sir i sent you the screenshots on your email.

**Comment by Soumyamessi** [comment]
Somebody help please....

**Comment by SubhamTyagi** [comment]
@Rishav-G this is font related problem. Change you phone font to default.

In next beta update i will enable tesseract. That would handle all font type.

**Comment by nsptraj** [comment]
Bro your are genius .the OCR not crush now.but I figure out some problems .when try to stop OCR it goes to profile its not stopping.and when I crop question and 3 options it takes question as 1 option and 3option not reading.

**Comment by Rishav-G** [comment]
Sir i will try today then in default font.

**Comment by SubhamTyagi** [comment]
@nsptraj Noted, in next beta update i will try to fix this.

**Comment by nsptraj** [comment]
Bro can you give tutorials for cropping the picture .loko hack

**Comment by vikram9494** [comment]
Sir it is working but not understanding croping to picture onces croping enough or not?
Please do demo video sir how to use it sirrrr

**Comment by nsptraj** [comment]
Bro I give few suggestions for loko hack.
1.provide 2 cropping one for question and one for options,also provide single crop for question and option. Which read question and options separately.
2.stopping OCR bug can fix.and selection of other profile.at a time.
Thank you bro

**Comment by SubhamTyagi** [comment]
In next beta update loko hack will store a screenshot image of area and a txt file of questions with options on 
```
external storage
```
for better bug fixes. In case of any problem these files will be helpful.
This options will optional

**Comment by dee9205** [comment]
Thus we need to take screenshot of whole questions and options ..together or separately for OCR .plz tell me

**Comment by Siddhartha619** [comment]
I Know Loko hack is best but cashshow per 6th question ke baad niche 25$ likha aa jata hai iss liye loko hack answer nhi deta

**Comment by trongvinhtv** [comment]
Hello, i'm using google translate so you sympathize for my english so bad.
Firstly, I thank you for creating this App, it's great. There are many bugs in this beta, so please fix it.
Next, I hope you can divide the area for OCR scanning more clearly. For example, we have to scan four times: the first is to scan the question, second, third, and fourth scan the answers. That would be very clear and convenient

**Comment by Rishav-G** [comment]
The problem you told is regarding font but there was no difference when i played woth default font
Same problem and also one major problem is that sometimes loko hack disappears from screen.

**Comment by nsptraj** [comment]
Bro same problem question reading as options. In latest beta version

**Comment by sumitsinhaa** [comment]
Link sir pls

**Comment by sumitsinhaa** [comment]
Linksir

**Comment by mithunbantai** [comment]
Shubham tyagi in my phone the OCR is working but when I click on stop OCR it does not stop please help
