### ISSUE TITLE
Problem on Ocr in 3 line question 

### ISSUE THREAD

**Issue by jahir90** [SubhamTyagi/loco-answers#159]
Great job.It is not crashing now. But When question is of 3 lines, it only divides the question in 3 parts and makes it as answer option. Original answer option is not read by Loko Hack then. 
Suggestion:
1. You may create an option to save question and answer option separately. 
2. Please Add an option to delete the saved screenshot. Otherwise we have to go phone settings every time to Clear data for deleting the screenshot.

**Comment by SubhamTyagi** [comment]
Just swipe right to left  the screenshot list it will delete

**Comment by jahir90** [comment]
Ok...done. Thanks

**Comment by nsptraj** [comment]
Bro your are genius .the OCR not crush now.not I figure out some problems .when try to stop OCR it goes to profile its not stopping.and when I crop question and 3 options it takes question as 1 option and 3option not reading.

**Comment by SubhamTyagi** [comment]
@Swadhin59 beta update is available now u you can download it
