### ISSUE TITLE
Request to Work in brainbaazi without using OCR

### ISSUE THREAD

**Issue by jahir90** [SubhamTyagi/loco-answers#164]
It will be the best if Loko Hack works in brainbaazi just as it works in loco, swoo and qureka. Then there will be no need of OCR search. I think It will be bug free then. Also OCR search takes more time than normal search.
Your work is awesome. No comparisons 👌👌👌👌👌

**Comment by royalchauhan** [comment]
Bro how does loko hack works in loco

**Comment by dee9205** [comment]
Yes royalchauhan you are right becoz in loco we are not able to take screenshot of questions and options. And for use of OCR we need screenshot..

**Comment by royalchauhan** [comment]
I have a solution for that . you can watch the live trivia videos of loco on youtube and the screenshot of the video on full screen

**Comment by royalchauhan** [comment]
Or you can use screencast to make video of trivia game and then take screenshot from the video.

**Comment by royalchauhan** [comment]
But the problem is that OCR of loko hack is not working it is showing app closed again and again.

**Comment by royalchauhan** [comment]
If you have a solution for that please comment

**Comment by jahir90** [comment]
In the old version of loco. Version 1.9.0. It works
