### ISSUE TITLE
Ocr issue same as LH 2.0 beta in beta3

### ISSUE THREAD

**Issue by mackesh** [SubhamTyagi/loco-answers#169]
Ocr in LH 2.0 beta 3 works only on 2 liner question same as LH2.0 beta2... App doesn't distinguish question part and option part... I already send u a snapshot of this issue when LH2.0 beta 2 released.. and same problem happened with our new Beta 3 version.... Sir make separate cropping of question and options.. our standard method works perfectly (without ocr)... But it supports limited trivia games... Great works with no words.. thanks

**Comment by SubhamTyagi** [comment]
This time LoKo HacK stored some file to phone storage (in dir /Loko Hack) 
Find the question and option txt file (start with QaOption_*****************.txt). post it here @mackesh

**Comment by mackesh** [comment]
PartnerAndaz Apna ApnaWhich is the only Hindi film
starring both Salman Khan and
Aamir han in lead roles?
Saajan

**Comment by mackesh** [comment]
This is in that text file... Actual question starts from which ******* roles?

**Comment by mackesh** [comment]
Which of these is the name of arinternational cricket stadium inIndia?
Eden gardens
Mughal gardens
Vrindavan gardens

**Comment by mackesh** [comment]
This is 2 liner so gives correct answer... Don't know how?

**Comment by SubhamTyagi** [comment]
> 
> 
> PartnerAndaz Apna ApnaWhich is the only Hindi film
> starring both Salman Khan and
> Aamir han in lead roles?
> Saajan

@mackesh this problem is not associated with loko hack this problem is related to Google OCR , 
Google OCR does not read the screen text properly

By the way i am working to port Google OCR to Tesseract
