### ISSUE TITLE
Still disappearing in redmi phones

### ISSUE THREAD

**Issue by Rishav-G** [SubhamTyagi/loco-answers#170]
I dont know if the disappearing problem persists for other mobile users too
But in redmi it is still happening

**Comment by pankajksu** [comment]
ocr not work properly.

**Comment by SubhamTyagi** [comment]
@Rishav-G send crash report.

**Comment by ronymandal** [comment]
Shubham sir u give new option (store question and option to storage) , how it works??

**Comment by SubhamTyagi** [comment]
@ronymandal this option is only for debug purpose.

**Comment by Rishav-G** [comment]
@SubhamTyagi 
It is not crashing but the main answer giving screen of hack disappears from screen.

If u want more info i can record the screen and send it.

**Comment by ronymandal** [comment]
Sir ocr again give answer in options after dividing question in 3 parts☹️

**Comment by Rishav-G** [comment]
@subhamtyagi what u meant by ip blocked?
