### ISSUE TITLE
OCR Problem

### ISSUE THREAD

**Issue by Kuldeep657** [SubhamTyagi/loco-answers#177]
Sir vahi problem hai ab bhi bs thoda sa sudhar hua hai ab "Swoo" ke to sahi de rha hai aur  "Loco" me options baali jagah question show kar rha hai ......
Iss problem ko door karo sir
OCR screen shot method baise to achha hai pr achchhe se work nhi kar rha hai 
Maine bahut tarah se set karke dekh liya swoo app me sahi work kar rha hai aur Loco' B Baazi ' Aur 'Qureka' in apps me work nhi kar rha hai option baali jagah questions de rha hai
 aur haan vo swipe karne pe delete to ho jata hai but thodi der me fir se aa jata hai delete hi nhi ho rha hai ........

**Comment by SubhamTyagi** [comment]
Send log file of that questions
