### ISSUE TITLE
Disappear

### ISSUE THREAD

**Issue by ronymandal** [SubhamTyagi/loco-answers#178]
Shubham sir between the game, sometimes it disappear and shows answers after tapping again and again then give ans. After 10 sec, late answer

**Comment by harshvhgzdd** [comment]
sir plese it is not supporting in version 4.4.4(kitkat) plese make this app to support in kitkat version because all my friend have kitkat version mobile plz plz plz support do in kitkat version😔😔😔😔😔😔😫😫😫😫😫🙏🙏🙏🙏🙏

**Comment by SubhamTyagi** [comment]
@harshvhgzdd this was the beta.

In beta app i targeted only some devices in stable version all devices supported

**Comment by SubhamTyagi** [comment]
@harshvhgzdd in stable version some more devices will be included

**Comment by ronymandal** [comment]
Sir 1st solve disappearing prblm plz🙏

**Comment by harshvhgzdd** [comment]
thanks for comment on my comment plese in stable version you add version 4.4.4(kitkat) version plz plz plz

**Comment by harshvhgzdd** [comment]
sir plese i want to your whtsapp no ya contact no
