### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by kvik1** [SubhamTyagi/loco-answers#197]
Hi it would be nice if you could add yippy.com and searx.me search engines

**Comment by SubhamTyagi** [comment]
Can you point out some advantages of these search engine over Google search engine

**Comment by kvik1** [comment]
I have used these search engines in another app for trivia they were more accurate than google and Bing on the results also startpage also provided better results but was slow

**Comment by Siddhartha619** [comment]
Bhai OCR Accha Hain But Ek Block Per Question & Option System Accha Nhi Hai
Usko Trivia Helper K Tarah Kar Do
