### ISSUE TITLE
App 100% working in OCR.having small bugs

### ISSUE THREAD

**Issue by nsptraj** [SubhamTyagi/loco-answers#200]
Bro your great ,OCR working great.I have small problem that when try to stop OCR it goes to profiles. Its not stopping.so I'm use force stop and start again to elect another profile.thank you bro.

**Comment by hackthon2018** [comment]
Is loco, brain Baazi,swoo all are working or not?

**Comment by jatinverma7** [comment]
Can u tell me how we use

**Comment by pankajksu** [comment]
OCR Ka searching speed agar Thora Jada hota to acha Hoga.

**Comment by ikhlas60** [comment]
If you want to stop over just go through your notification bar above
