### ISSUE TITLE
Setting issue

### ISSUE THREAD

**Issue by jatinverma7** [SubhamTyagi/loco-answers#212]
Hey 
When i open app and go in setting 
He says 
Download ocr files 
Pls wait 

After 10 to 20 min nothing happend

**Comment by ikhlas60** [comment]
I've is not working 
it shows could not read options

**Comment by SubhamTyagi** [comment]
Check screenshot file in LoKo HacK folder

**Comment by aryanraj0** [comment]
Sir app instal ke baad setting me kya Karna hai aur loco brain bazi  ka screenshot link please de do because app not given ans please help me
