### ISSUE TITLE
1 issue regarding overlay

### ISSUE THREAD

**Issue by jahir90** [SubhamTyagi/loco-answers#215]
I recently updated my phone to Android oreo. There was a button " Tap to hide Loko Hack overlay" in notification in previois Android Nougat. But here I could not find. So inside the app I press "Stop ocr" but instead of stopping it takes to the screenshot page everytime.
Suggestion:
1. Please enact the "Stop Ocr" Option properly to Remove the overlay.

Otherwise no issues. Working very fine.

**Comment by patnaiksubrat** [comment]
I have also face this problem with Android Pie. There is no stop option in OCR overlay so I always restart my phone to close the OCR

**Comment by jahir90** [comment]
U may go to app settings to force stop instead of restart the phone Until solution comes

**Comment by SubhamTyagi** [comment]
fixed in  version 2.1
