### ISSUE TITLE
Settings not working in trivia hack

### ISSUE THREAD

**Issue by joukyuu** [SubhamTyagi/loco-answers#219]
On clicking settings app closes...my phone lenovo k8 note...Oreo...also can you make the cropping into two sections, 1 for question and 2 for answers...also could you make it so that we can even play "4 options games" as well...

**Comment by n9u** [comment]
Same issue happened with me , and yesterday  I played swoo with loco hack v 2.0 and it gives me about 5 wrong answers

**Comment by SubhamTyagi** [comment]
Noted

**Comment by SubhamTyagi** [comment]
fixed
