### ISSUE TITLE
How search is made by trivia hack...???

### ISSUE THREAD

**Issue by joukyuu** [SubhamTyagi/loco-answers#221]
Hey bro shubham ...how's the search made by trivia hack...one is Google search with only question while the other search is ?????

**Comment by SubhamTyagi** [comment]
https://github.com/SubhamTyagi/loco-answers/blob/efe942cc6759bf3c68a707099d1eaadea8cae9f3/app/src/main/java/ai/loko/hk/ui/answers/Engine.java

Check this file

**Comment by SubhamTyagi** [comment]
i had provided a option to add custom search engine.

**Comment by SubhamTyagi** [comment]
> 
> 
> I think "instead of wiki" second search...question + all the other options should be "googled" and result displayed...well at the end it's upto you to decide...also could you add "teoma" search engine...it's results are very much similar to google...could you change the colour of the logo please..."grey doesn't look good"...."black" should be just good...

if we use this time taken by app will be 3x time

**Comment by SubhamTyagi** [comment]
Today work is my last work 😭
