### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by 3D-GaminG** [SubhamTyagi/loco-answers#222]
For No/Not/Never search the question without the No/Not/Never word and the option with the lease score will always be the right answer. As Google many a times understand a not question and gives respective pages in search giving the right option high score and app saying it is the wrong option as the app knows lower score will be the right option

**Comment by SubhamTyagi** [comment]
This is already done check it here [Line 73](https://github.com/SubhamTyagi/loco-answers/blob/efe942cc6759bf3c68a707099d1eaadea8cae9f3/app/src/main/java/ai/loko/hk/ui/answers/Engine.java#L73)
