### ISSUE TITLE
ocr and tesseract

### ISSUE THREAD

**Issue by n9u** [SubhamTyagi/loco-answers#225]
i don't know how to use the OCR and the Tesseract  , even that i don't know what they will do that exceed the normal search engine .

**Comment by SubhamTyagi** [comment]
Tesseract is a ocr  which is similar  is Googl vision ocr

**Comment by n9u** [comment]
which one is the best to use with swoo ?
like i told you that i tried the last version with Swoo yesterday and it gave me more than 5 wrong answers.

**Comment by ikhlas60** [comment]
Ocr gives the answers too late

**Comment by n9u** [comment]
I have tried the OCR yesterday and it didn't work
