### ISSUE TITLE
Text Recognition

### ISSUE THREAD

**Issue by sahilrajpal121** [SubhamTyagi/loco-answers#228]
Most of the times it can't recognise what is question and what is answer...because of that sometimes it searches half the question and half the Question (like in next line) is shown as a option...i have tried every type of cropping...it wont work unless u make a feature to crop questions and options seperately...thank you

**Comment by SubhamTyagi** [comment]
Don't use fast method for OCR 
Or either use tesseract ocr

**Comment by sahilrajpal121** [comment]
Helps..but it still fails on 3 lines q  and ocr can't work on apps like hangtime...for that different cropping is required...all the way...nice update
