### ISSUE TITLE
Screenshot problem

### ISSUE THREAD

**Issue by ayushhasani2004** [SubhamTyagi/loco-answers#232]
I am not able to take screenshot of my swoo the app is not allowing me to take screenshot please help me what I have to do now

**Comment by Prakashjainbp** [comment]
U can't take screenshots in swoo and loco latest version they block it

**Comment by hackthon2018** [comment]
Now what can we do for getting the screenshots??

**Comment by dee9205** [comment]
Same problem ..shubham bro plz suggest us.

**Comment by Jaypatel2710** [comment]
Download virtual xposed and then add disable flag secure module in it. After that install the module and loco in virtual xposed together. It works for all apps

**Comment by dee9205** [comment]
Can you please make a screen video of this tutorial..

**Comment by ayushhasani2004** [comment]
Give me your WhatsApp or email I will send you screenshot which I captured

**Comment by dee9205** [comment]
9205451911 and email is deepakkumar8743@gmail.com

**Comment by ayushhasani2004** [comment]
Screenshot sender to your gmail

**Comment by dee9205** [comment]
bro i didn't receive any screeshot plz send again.
email- deepakkumar8743@gmail.com
