### ISSUE TITLE
Not working in HQ

### ISSUE THREAD

**Issue by shinestar9101987** [SubhamTyagi/loco-answers#234]
Sir its not working on HQ

**Comment by dee9205** [comment]
🤨🤨🤨🤔 after released this version , there is not a game yet (HQ). Timing of next game is 6:30 Am , sunday . How can you say that..???
And it is working very well in hq ...
And sorry for poor english 🙄

**Comment by ajith1y** [comment]
Are you any money to subhamtyagi

**Comment by ajith1y** [comment]
Are paid any money to subhamtyagi?
