### ISSUE TITLE
Answers not giving

### ISSUE THREAD

**Issue by Ashishsewani** [SubhamTyagi/loco-answers#245]
Sir,
The app is just working correctly with Swoo and Qureka . And not working with loco and brainbaazi and HQ even after adding screenshots of live questions . Please help me with it . Desperately waiting for it to work with Loco and other games. Please help me Sir.

**Comment by Surajit23** [comment]
Sir ye app loco mei work nehi kor raha hai....scan failed dikha Raha hai and answer nehi de Raha hai...
