### ISSUE TITLE
Suggestion...

### ISSUE THREAD

**Issue by pankajksu** [SubhamTyagi/loco-answers#248]
sir , mera ek reqst hai , aap OCR ko jada importent mat de , usse accha aap app ki answer accuracy k uper kaam kare jab app 90% se 100% answer dene lage tab app OCR ko importent de. .

**Comment by dee9205** [comment]
Yes bro ... accessibility start not working well.. it give wrong ans mostly . But ocr works good in qureka.

**Comment by naveenbbbbb** [comment]
Yes thanx

**Comment by pankajksu** [comment]
Bohut Jada wrong answer de Raha hai. Plssssssss sir Kuch kijiye.
