### ISSUE TITLE
Accuracy 70-80 %

### ISSUE THREAD

**Issue by deepakkumarraj2704** [SubhamTyagi/loco-answers#249]
Sir isse pahle waale version accuracy 80-90% tha kabhi kabhi 100% bhi answer sahi deta tha lekin new version me ab bahut saare wrong answer de raha he plz sir next update me old version ka formula new version me daale ya phir kuchh kijiye💯💯

**Comment by SubhamTyagi** [comment]
I didn't change anything in search engine.  Always try Google search engine

**Comment by Dpereiraa** [comment]
Inspite of having a good Jio connect m not able to use Loko hack I have to use VPN please find a way for the app to work on any internet connection
