### ISSUE TITLE
Motog5 plus

### ISSUE THREAD

**Issue by rajaaryan1994** [SubhamTyagi/loco-answers#255]
Hello, shubham tyagi, dear there is a problem with new update and after Oreo upadate in motog5 plus loko hack not working on my phone plz do something 4 it.

**Comment by naveenbbbbb** [comment]
Same here bro

**Comment by SubhamTyagi** [comment]
Send crash report or elaborate you problem.

**Comment by dinesh1024** [comment]
on oreo ,app is not showing answers

**Comment by rajaaryan1994** [comment]
I just try on qureka it was working but on swoo trivia its not working only finding answer....

**Comment by rajaaryan1994** [comment]
After updating the app problem was not solved...😢..not working on swoo trivia...plz do something..bro...
