### ISSUE TITLE
For Everyone!!!!

### ISSUE THREAD

**Issue by meuserhere** [SubhamTyagi/loco-answers#263]
Earlier it worked with HQ 1.6.2 and gave best accuracy among all other helper and bot, but now its not working at all other than OCR mode. And too many wrong answers while I use OCR. 
If it is still working on HQ 1.6.2 please comment

**Comment by SubhamTyagi** [comment]
Yes, Accessibility method also work with HQ 1.6.2 version

**Comment by meuserhere** [comment]
Its been 5/6 days, Accessibility method is not working with HQ 1.6.2 anymore. Please look after that and fix the issue sir. 
This is the only helper i can trust and i am comfortable with.
