### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by Adityanair8895** [SubhamTyagi/loco-answers#264]
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at ai.loko.hk.ui.answers.WikiSearch.run(WikiSearch.java:73)
-----------------

Device Information

DEVICE.ID : c9e4b0dc7c8f14bc
USER.ID : 
APP.VERSION : 23
LAUNCHER.APP : net.oneplus.launcher
TIMEZONE : Asia/Kolkata
VERSION.RELEASE : 8.0.0
VERSION.INCREMENTAL : 1809142047
VERSION.SDK.NUMBER : 26
BOARD : msm8996
BOOTLOADER : unknown
BRAND : OnePlus
CPU_ABI : armeabi-v7a
CPU_ABI2 : armeabi
DISPLAY : ONEPLUS A3003_16_180914
FINGERPRINT : OnePlus/OnePlus3/OnePlus3:8.0.0/OPR1.170623.032/1809142047:user/release-keys
HARDWARE : qcom
HOST : ubuntu-117
ID : OPR1.170623.032
MANUFACTURER : OnePlus
MODEL : ONEPLUS A3003
PRODUCT : OnePlus3
SERIAL : dea08d60
TAGS : release-keys
TIME : 1536931201000
TYPE : user
UNKNOWN : unknown
USER : OnePlus

**Comment by sum21an** [comment]
Same problem
