### ISSUE TITLE
Displays wrong option

### ISSUE THREAD

**Issue by RaviSRanjan26** [SubhamTyagi/loco-answers#271]
Bro.. i scanned the entire question & options in loco..but in the app interface i get the question's last line in The first option & second option. It happens most times in loco. 

I have tried all crop. Right from the point where questions is..to the point where the countdown clock is . But same thing. 

![screenshot_2018-10-12-20-07-40](https://user-images.githubusercontent.com/44061900/46938485-8e350c80-d081-11e8-8eee-ade64dcc447d.png)

**Comment by SubhamTyagi** [comment]
Is you switched on  FAST MODE FOR OCR. If yes then either switch  off this or try tesseract ocr. 

You may try this in new version of Trivia hack 2.1.2

**Comment by desairam** [comment]
It may be because you got eliminated and question position shifted because of it
