### ISSUE TITLE
Performance still need improvement

### ISSUE THREAD

**Issue by ombharti7** [SubhamTyagi/loco-answers#284]
Hi Subham sir,
The performance of the app ceases when there is any number option question, in few questions it giving 0 count in all the options so difficult to choose the correct one. In this version the app is crashing frequently. Please rectify it ,waiting for a much better upgrade.

**Comment by hackthon2018** [comment]
Yaa I agree with the @ombharti7 
It is giving wrong answers most of the time from yesterday... Please look  into this..

**Comment by sahilrajpal121** [comment]
That's Beacuse trivia apps are becoming smarter and try to put in more anit-bot questions... accuracy could be increased by addding one's own dictionary to ignore thing... which could in specific games and could be changed anytime as we usually know the pattern of Question making of almost every trivia app..and one more thing... if you could add up the feature of cropping Question and options seperately... it would help in apps like hangtime...thank you @SubhamTyagi
