### ISSUE TITLE
Preview of no count

### ISSUE THREAD

**Issue by joukyuu** [SubhamTyagi/loco-answers#293]
![screenshot_20181018-123310](https://user-images.githubusercontent.com/43905435/47136747-4eb12f00-d2d2-11e8-8dcc-748b941ab87d.png)

**Comment by vikram9494** [comment]
joukyuu use ocr giving corrects accessibility not working properly giving lot of wrongs compare to Ocr is best...can i talk with you onces.

**Comment by joukyuu** [comment]
Can't use ocr trivia hack with trivia helper at the same time...default trivia hack gives most of counts 0...

**Comment by vikram9494** [comment]
oh ok...

**Comment by Anspri143** [comment]
Joukyuu Bro Plzz tell me that application name.. I mean that application In blue colour . Which app is this?

**Comment by SubhamTyagi** [comment]
In this case Google want to verify against Automated search.
