### ISSUE TITLE
Logo Design Proposal

### ISSUE THREAD

**Issue by debpedrano** [SubhamTyagi/loco-answers#329]
Greetings to you Project Owner!

I am a graphics designer who make logo for GitHub projects, I am not a professional one but I can give you a good quality output. It would be a benefit to the project since it is getting bigger and bigger, so its on you to decide if you need it. Just mention me in the comment section and lets discuss about it.

**Comment by SubhamTyagi** [comment]
https://github.com/SubhamTyagi/loco-answers/issues/60

you can find the current logo [here](https://github.com/SubhamTyagi/loco-answers/blob/master/app/src/main/res/mipmap-hdpi/ic_launcher.png)
and find contribution guide or license [here](https://github.com/SubhamTyagi/loco-answers/blob/master/LICENSE)

@debpedrano

**Comment by debpedrano** [comment]
I created this issue because I was not so active on that past issue because of studies and now I am free to work. I have on my mind creating new logo not just the LH, so that it will be more attractive.

**Comment by debpedrano** [comment]
@SubhamTyagi 

This is my final output, any suggestions?

![image](https://user-images.githubusercontent.com/40510200/47826554-87add100-ddb3-11e8-9886-5b456dfbc450.png)

**Comment by SubhamTyagi** [comment]
could you update above icon with following colors
L color(#3D5AFE )(A400)
Questions mark color(#D32F2F, 211, 47, 47)(700)
H color is same as above.

**Comment by debpedrano** [comment]
![image](https://user-images.githubusercontent.com/40510200/47829342-f4c86300-ddc1-11e8-87b8-aaae59f8c0ab.png)

@SubhamTyagi

**Comment by SubhamTyagi** [comment]
@debpedrano your original logo have pretty cool colors, thanks!

 you are welcome to make pull request for this.

**Comment by debpedrano** [comment]
Great! I'll be sending PR later. One more thing, if you have any projects that needs a logo, please don't hesitate to contact or mention me on that particular project. 

email: debpedrano18@gmail.com

**Comment by SubhamTyagi** [comment]
thanks

**Comment by debpedrano** [comment]
Is this okay for ReadMe Banner?

![image](https://user-images.githubusercontent.com/40510200/47849601-43e7b580-de0d-11e8-8173-f72c69ecb711.png)

**Comment by SubhamTyagi** [comment]
@debpedrano Name is **TRIVIA HACK**

**Comment by debpedrano** [comment]
@SubhamTyagi

**Comment by debpedrano** [comment]
do you need this kind of logo with outer shapes? 

![image](https://user-images.githubusercontent.com/40510200/47863477-53c5c080-de32-11e8-95d0-e10d5c1ec7f2.png)

**Comment by SubhamTyagi** [comment]
@debpedrano i think outer shaped icons are deprecated and most of apps doesn't have these types of icon.

**Comment by debpedrano** [comment]
@SubhamTyagi  Hello, in making a PR. Should i include the black and white version ? or only the main logo? 
I will include svg also which contains all the stuffs.

**Comment by SubhamTyagi** [comment]
@debpedrano hello,i have merged the PR.  Now app is live with new icon. i had added your contribution in project readme file. you can close this issue now.

Thanks

**Comment by debpedrano** [comment]
@SubhamTyagi  Thank you so much for trusting! have a great day, and you can always count on me if you need logo for your another project!... Thanks and more power!
