### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by nanajitang** [SubhamTyagi/loco-answers#341]
I downloaded this new version 2.2
But I can't install it
All previous version are there in my phone I can easily install it but this version I cannot 
Help me with this

**Comment by SubhamTyagi** [comment]
provide more details , screenshot etc

**Comment by nanajitang** [comment]
Ok

**Comment by nanajitang** [comment]
![screenshot_20181103-051924](https://user-images.githubusercontent.com/44707543/47945523-9b2e7880-df28-11e8-869a-72bd75496ac2.png)

**Comment by nanajitang** [comment]
This is happening all time
In this version
When I am installing it it's name is not shown up unknown is written in place of it's name
But the previous version are good I can install them easily.

**Comment by marishlalwani** [comment]
I have the exact same problem on Android Oreo 8.0

**Comment by SubhamTyagi** [comment]
@nanajitang 
 install new version 2.2.1

**Comment by marishlalwani** [comment]
Working fine on Android 8.1. 8.0 is the issue !
