### ISSUE TITLE
arabic language 

### ISSUE THREAD

**Issue by XxBlackHeartxX** [SubhamTyagi/loco-answers#358]
**Describe the bug**
does this program support arabic language ? ! i  test this program in T-go an arabian game and the game show a bugand  there  is no answer however i use tesseract *ocr* .it take so much time then bug 
**To Reproduce**
1. Go to '
![45537025_316779622489248_2685003924695416832_n](https://user-images.githubusercontent.com/44852172/48225320-1d91bf00-e3a5-11e8-9915-a85fb71df97e.png)

...'

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):** - OS: [e.g. Pie]
 - Version [e.g. 8.1]

**Additional context**

**Comment by SubhamTyagi** [comment]
yes it works
