### ISSUE TITLE
Need Loko Hack 1.6.2-smart version

### ISSUE THREAD

**Issue by Shibam007** [SubhamTyagi/loco-answers#38]
please avail a link of loko hack 1.6.2-smart version which was best for me.but i replaced it with latest 1.71-chetah and it's not working with speed n smoothness. And present loko hack 1.6.2 in your page is chetah version. so please avail a link of loko hack 1.62-smart version sir

**Comment by ErSurajGupta** [comment]
Bro your previous version 1.7.0 was an excellent and speed was also good,this latest version 1.7.1 is very very slow and sometimes it doesn't  even show the answers.plz fix it

**Comment by ErSurajGupta** [comment]
And 1 more problem i m facing with this version is that it gives answer after pressing the button more than thrice due to which i got eliminated several times from the games.

**Comment by SubhamTyagi** [comment]
all problem fixed in new version till this date loko-hack 1.7.3 is fastest and most accurate
update your app to version 1.7.3
