### ISSUE TITLE
Please make one but full and final update

### ISSUE THREAD

**Issue by loserboyalim** [SubhamTyagi/loco-answers#391]
Hello shubham tyagi,
I just want to say you that each of your update have some issues. So please take your time and fix all the bugs that you are trying to fix since you create this app.
All are expecting something best from you on your best update.
I am telling this to you because when I started ocr In your new update 2.2.2, 5/10 questions it shows 0,0,0 in all the three options. Please fix this problem.
If nobody there,I am expecting not better but best from you.
                                                        Good luck
                                                 Your well-wisher

**Comment by SubhamTyagi** [comment]
thanks:

**Comment by loserboyalim** [comment]
Hmm please. And also I am noticed one more major problem that your app's ocr doesn't show answer of that questions which options are in numerical form.
Please fix this and also I say you only one thing make one but final update.
👍👍👍😎😎😎👑
