### ISSUE TITLE
About json file missing

### ISSUE THREAD

**Issue by srbsppatil** [SubhamTyagi/loco-answers#393]
Hello Sir,
Im working on your app for some modifications in it,but the json file is missing in the the source code ,can you please pass the file or else can give firebase access where you created the app

**Comment by srbsppatil** [comment]
My email is srb.sp.patil@gmail.com

**Comment by srbsppatil** [comment]
Please reply

**Comment by SubhamTyagi** [comment]
Either use newer codes or you can disable firebase integration or you can create your own firebase account! it is not a helpful for you nor me if i provide api keys file.

**Comment by srbsppatil** [comment]
Ok fine,one thing i need is
The JSK file and pwd for app build of release mode

**Comment by srbsppatil** [comment]
That would be very helpful cause im very near to modifications

**Comment by srbsppatil** [comment]
Please reply

**Comment by SubhamTyagi** [comment]
@srbsppatil find it [here](https://developer.android.com/studio/publish/app-signing)

**Comment by srbsppatil** [comment]
Thank you

**Comment by srbsppatil** [comment]
Your GREAT WORK has made me realise my worth and get my Life on Track after long time SIR,!!!!!!!

Thank You So much

**Comment by SubhamTyagi** [comment]
@srbsppatil 
is your app running working?

can you send me the apk file which you created!
