### ISSUE TITLE
Tesseract 4.0 beta 

### ISSUE THREAD

**Issue by cuongtora1996** [SubhamTyagi/loco-answers#399]
**Is your feature request related to a problem? Please describe.**
Please add Tesseract 4.0
**Describe the solution you'd like**
I know that Google Vision is faster and cleaner than Tesseract OCR but the 4.0 version is release. Can we try it out?

**Describe alternatives you've considered**

**Additional context**

**Comment by SubhamTyagi** [comment]
@cuongtora1996  
yes ,you can try it latest version updated tesseract to 4.0.0 👍

**Comment by cuongtora1996** [comment]
Thank you my man!
