### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by Jayanthbm** [SubhamTyagi/loco-answers#4]
Not working on oreo  based roms  in oreo based roms app keep on stopping and also on nougat  rom app opened but showing no results

**Comment by SubhamTyagi** [comment]
Bug fixed for Android Oreo update this at

https://github.com/SubhamTyagi/loco-answers/releases/tag/V1.5.1

**Comment by Sachin14325** [comment]
Sir brain Baazi ka koi new app layo sir please

**Comment by Ashishrocker** [comment]
Bro can you provude your phone number please
