### ISSUE TITLE
Fail to detect language by places nouns

### ISSUE THREAD

**Issue by popeyaho** [SubhamTyagi/loco-answers#401]
**Describe the bug**
If the main language is not English, but the option is English and they are the nouns. The result seems to be broken

**Expected behavior**
Show true words, if possible, show the question for clear

**Screenshots**
https://i.imgur.com/Adhmh4n.png

**Smartphone (please complete the following information):**
 - Device: Xiaomi
 - OS: Android
 - Version 2.2.2

**Additional context**
if possible, show the question for clear

**Comment by SubhamTyagi** [comment]
which OCR (Tesseract or Google vision) you are using?

**Comment by popeyaho** [comment]
I'm using Vietnamese for main language

**Comment by SubhamTyagi** [comment]
i will update Tesseract to 4.0.0 as soon as possible #399

**Comment by SubhamTyagi** [comment]
i expect this bug will be resolved in that version

**Comment by popeyaho** [comment]
Thank you, I'm waiting for you!

**Comment by SubhamTyagi** [comment]
@popeyaho 
In latest version i updated Tesseract version to 4.0.0 and used [fast data](https://github.com/tesseract-ocr/tessdata_fast) files

**Comment by popeyaho** [comment]
@SubhamTyagi thank you for the update, seems to be scan better
