### ISSUE TITLE
TH for iOS

### ISSUE THREAD

**Issue by srbsppatil** [SubhamTyagi/loco-answers#407]
Can you please make TH for iOS ,we are unable to use it in iphone lot of my friends have iphones

**Comment by SubhamTyagi** [comment]
The ios app development is not great for me as developers program have fee [$99/year](https://developer.apple.com/support/purchase-activation/) and as i develop apps as my hobby not for profits.

**Comment by srbsppatil** [comment]
Ohh yes i know,but is there any chance that i can use the TH code to make it for ios from some other developer,i know people here in italy who are developer....will you allow this?

**Comment by SubhamTyagi** [comment]
yes,
 anybody can do whatever they want with this app as gpl3

**Comment by srbsppatil** [comment]
One more problem we face is that,sometime the overlay box covers the questions 1st line in some trivia,this doesn't produce the answer as it picks the question then...... provide any option to reduce the box size according to need .... consider this in next update
