### ISSUE TITLE
Bing website is not working in trivia hack..Pls fix

### ISSUE THREAD

**Issue by snehithpvp** [SubhamTyagi/loco-answers#422]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung]
 - OS: [e.g. Pie]

**Additional context**

**Comment by SubhamTyagi** [comment]
@snehithpvp is google search is working?

**Comment by snehithpvp** [comment]
Yeh Google Is Working bro

But Bing is not working
Bing search is smooth to get answer. i like bing
If there is a error Pls Fix it bro.

**Comment by snehithpvp** [comment]
From 2days onwards it is not working in my friends mobile also
Not only bing ask and yahoo and duckduckgo is not working
Only google is working
