### ISSUE TITLE
M

### ISSUE THREAD

**Issue by snehithpvp** [SubhamTyagi/loco-answers#423]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung]
 - OS: [e.g. Pie]

**Additional context**

**Comment by SubhamTyagi** [comment]
@snehithpvp  Bing and other search engine shows captcha code more often than google if these detect automated search query. 

Other similar paid apps may be using paid search query program of various search engines so these apps may not have failing in search query. As this app is free open source and doesn't not using any paid partnership with any search engine like other paid apps.

Temporary  i suggest you to use Google  search engine.
if you provide any screenshot or any log i will help you

**Comment by snehithpvp** [comment]
Bro Are you fixing?

**Comment by snehithpvp** [comment]
Bro.Plss Reply
Pls Fix it bro
I think there is error
Pls fix bing and yahoo error

2days back its sooo good
After that it not working

I tried in other ip address too
But getting problem. Answers are not getting

Pls fix bing and yahoo search engine bro

Pls reply me bro are you fixing or not?

**Comment by snehithpvp** [comment]
Which Screen shots and Which Log you want Bro?  Can you tell me , i'll send
you that screen shots and Log

**Comment by snehithpvp** [comment]
Bro...tell mw which screen shot want to send

**Comment by snehithpvp** [comment]
Which log are you asking?
