### ISSUE TITLE
It gives at least one wrong answer

### ISSUE THREAD

**Issue by udaikumar26** [SubhamTyagi/loco-answers#425]
**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung]: Motorola G5
 - OS: [e.g. Pie]: Oreo

It gives at least one wrong answer(accuracy of the app is 80-90%). For example below is a sample question for which it gave wrong answer.

Amitabh bachchan Was not a part of the debut film of which of these actress.
A. Shraddha Kapoor
B. Kareena Kapoor
C. Katrina Kaif

The app gave answer as 'A' but the correct answer is 'B'. 

This is happening when using OCR mode(start OCR option)

**Comment by SubhamTyagi** [comment]
Remember nobody  is perfect. 
This is only a helper app not a omniscient 😄. 
Just search this question on google( or any other search engine which is set by you) and see result and deduce right answer. btw '_**which of these**_'  type questions are hard to tackle on any search engine
