### ISSUE TITLE
Search process is done twice.

### ISSUE THREAD

**Issue by bompfn** [SubhamTyagi/loco-answers#428]
Hey, 

thanks for this gr8 piece of work! (or maybe call it art?)

I've done a little research on this masterpice of code but I'm not able to understand why the "search" function 
(synchronized public String search()... ) in /app/src/main/java/ai/loko/hk/ui/answers/Engine.java is triggered twice. 

Since the "normal google search" is locking you out at some amount of requests it would help me a lot to "only send 1 request" for one itteration. 

Could you please point the reason and the cause (calling function) for this "happens twice phenomen" out to me? 

Thank you very much!

Regards
ALi

**Comment by SubhamTyagi** [comment]
i am aware of this issue. i also couldn't find the cause of this.

i will do more testing for this again but i am bit sure it caused by Screenshotter.java class
