### ISSUE TITLE
Loko hack not working

### ISSUE THREAD

**Issue by Mohan2282** [SubhamTyagi/loco-answers#45]
Loko hack is not giving answers 
Not displaying the answers plz solve the problem and
provide your paytm number we will help you for give some money to contribution to your project ,Give a new update with your paytm number to donate from users Like PayPal ,thank u bro your r a good developer thank u very much previously the Loko hack give 90°/. Accuracy rate it's working on HQ TRAVIA awesomely And Qureka also now it's not working with any Travia games  solve this issue faster bro I hope that you this issue fastly thank u bro

**Comment by SubhamTyagi** [comment]
fixed in latest version
