### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by billa1234** [SubhamTyagi/loco-answers#46]
It doesn't give any responseen tapped on Simple or advanced. Tried installing previous version but happened same.

**Comment by chanx74** [comment]
Fixed the issue. 
If using jio 4g as ur carrier just use apn settings 
1)APN = jionet
2)proxy,port,uname,password => not set
3)server => www.jio.com
4)MCC and MNC => default values
5)authentication => none
6)APN type => default, xcap
7)APN(roaming as well) => IPV4
8)Bearer => LTE
9)MVNO type => SPN
10)MVNO value => Jio 4G(case-senitive)

Save the apn settings and test with any live trivia game 

Cheers, 
Chanaksha

**Comment by Mohan2282** [comment]
Bro IAm using jiofi what can I do now bro
