### ISSUE TITLE
Can't support you via PayPal

### ISSUE THREAD

**Issue by Safiksawan** [SubhamTyagi/loco-answers#47]
I wanted to donate Rs 200 via paypal but i am unable to do so because it says" the recipient is unable to receive payment".

**Comment by Safiksawan** [comment]
Also please update loco hack 1.7.1 as it is not working on any trivia games on any version.

**Comment by SubhamTyagi** [comment]
i will update app soon 
you can contact me at shubham2tyagi7@gmail.com or [here](mailto:shubham2tyagi7@gmail.com)

**Comment by SubhamTyagi** [comment]
new update is available
