### ISSUE TITLE
Look hack 1.7.1 not working 

### ISSUE THREAD

**Issue by sshailesh072** [SubhamTyagi/loco-answers#49]
Sir Maine jab update Kiya 1.7.0 to 1.7.1 me to fir bus 1_2 din answer show huye fir aana bannd hogye and fir Maine old version dala to usme bhi nhi aarahe....plzzz suggest what should I do

**Comment by SubhamTyagi** [comment]
i will update app soon..

**Comment by Mohan2282** [comment]
Give a new update with your suggested paytm number

**Comment by sshailesh072** [comment]
Leave a commentsir plz abhi to aap koi solution Bata dijiye.maine mobile bhi formet karliya but much nhi ho raha

**Comment by sshailesh072** [comment]
Sir this is Shailesh shrivastava I need your help sir

**Comment by gupta0708** [comment]
Bro loco letest version work only wife network so please solve this problem

**Comment by SubhamTyagi** [comment]
new update is available
