### ISSUE TITLE
App doesn't work

### ISSUE THREAD

**Issue by Raj4everr** [SubhamTyagi/loco-answers#56]
In swagiq app doesn't work....it keeps showing "some error occured"....

**Comment by Mohan2282** [comment]
Yes it's 'Something' error occured

**Comment by SubhamTyagi** [comment]
SwagIQ timing is around 5 AM IST . That time i am not able to play SwagIQ and test LoKo HacK

If you capture the screenshot and dump file with **uiautomator** then send it me

**Comment by Raj4everr** [comment]
Uiautomator....???how do i do that on my android phone...

**Comment by SI-VANI** [comment]
Loko app is not working properly sometime show answers sometime not working what is the problem plz tell me
