### ISSUE TITLE
Project Enhancement

### ISSUE THREAD

**Issue by debpedrano** [SubhamTyagi/loco-answers#60]

**Comment by debpedrano** [comment]
Good day to you ! 
I am a designer and making some logo, is there anything I can help to make your project look awesome ?

**Comment by SubhamTyagi** [comment]
This app logo is not attractive, could you make a attractive, awesome logo for this

**Comment by debpedrano** [comment]
sure ! can I see the current logo, just to get an idea on it @SubhamTyagi  . or maybe I will create something new for the project, what you prefer ?

**Comment by SubhamTyagi** [comment]
[here](loco-answers/app/src/main/ic_launcher-web.png) you can find the current icon, you can also create a new icon for this

**Comment by debpedrano** [comment]
sorry for the late response, I was so busy this past few days. I will make the design now and ill comment it here as soon as I am done. Thank you ! @SubhamTyagi
