### ISSUE TITLE
blank no answer

### ISSUE THREAD

**Issue by Pritam1122** [SubhamTyagi/loco-answers#70]
since yesterday it show blank in qureka and swoo plzz solve it sir

**Comment by Pritam1122** [comment]
sir everyone wants to support u but we are not getting a direct option

**Comment by Pritam1122** [comment]
sir in next version include a direct payment method to u

**Comment by ronymandal** [comment]
I have only paytm

**Comment by SubhamTyagi** [comment]
For this bug i will collect some more data about this bug(in beta version of 1.7.5). I assured you that In next version i. e. 1.7.5 stable (not beta) it will be fully resolved. I did my best for this in 1.7.4 stable version ( but we have to **remember nothing is perfect**)

**Comment by sourav840** [comment]
Did this app worked in tonight's loco game??
