### ISSUE TITLE
BRO AFTER UPDATE IT IS GIVING ALL ANSWERS RIGHT BUT THE LAST ANSWER IS ALWAYS WRONG WHETHER THE APP IS QUREKA OR SWOO. PLEASE DO SOMETHING IF YOU CAN DO ABOUT IT OTHERWISE YOU APP IS BEST AND THANKS FOR READING AND RESPONDING.

### ISSUE THREAD

**Issue by royalchauhan** [SubhamTyagi/loco-answers#72]

**Comment by ronymandal** [comment]
Brother u have no issue about blank overlay or u have a solution for that

**Comment by royalchauhan** [comment]
No I don't have that issue bro it is working fine. This app is better than
any trivia hack app use it.

**Comment by ronymandal** [comment]
I know this is best app , and i also use this but i have problem for blank overlay

**Comment by ronymandal** [comment]
Any solution for that??

**Comment by SubhamTyagi** [comment]
For this bug i will collect some more data about this bug(in beta version of 1.7.5). I assured you that In next version i. e. 1.7.5 stable (not beta) it will be fully resolved.  I did my best for this in 1.7.4 stable version ( but we have to **remember nothing is perfect**)

**Comment by Pritam1122** [comment]
Bro it's not working in Redmi note 4

**Comment by aryanraj0** [comment]
Please somebody give me 2.0 link
