### ISSUE TITLE
Maximum time blank in Redmi note 4 

### ISSUE THREAD

**Issue by Pritam1122** [SubhamTyagi/loco-answers#78]
Sir it's working in other mobile but almost all time blank interface in Redmi note 4 😞

**Comment by deviladitya** [comment]
Bro jio ke network se nhi work kr rha hai

**Comment by gupta0708** [comment]
Airtel use karo

**Comment by Pritam1122** [comment]
Really n broo
Ok I will try

**Comment by SubhamTyagi** [comment]
I have test this app on wide range of phone with combination of networks. I didn't find these type of error. If you could tell me the the procedure for reproducing the error.
