### ISSUE TITLE
Qureka Issues  Serious 

### ISSUE THREAD

**Issue by rahuldeopa** [SubhamTyagi/loco-answers#9]
I found that your app is givig wrong answer in last two question.
I think that Qureka found permanent antidore of your app.
The questions are negitive eg- which of this is incorrectly paired etc.
And always in these types of questions. 
Hope you work on it and get us a new app showing Qureka that you are also clever .
Although it work insane in first 6 question.
You are doing great work .
Keep it.

**Comment by SubhamTyagi** [comment]
update app
