### ISSUE TITLE
Not working with loco app

### ISSUE THREAD

**Issue by Parth4337** [SubhamTyagi/loco-answers#91]
I have tried multiple times in demo mode, but it just doesn't get any answers. If I put a question in Test Section within the app, it works and answers are accurate. But when I try in demo mode, it just gets stuck on finding for like ever. I used it on the first question of demo mode and gave it like 30 minutes but it is just stuck on finding answers.

**Comment by selenamariogomez** [comment]
Now not work for qureka.   Test mode also not working... help me

**Comment by SubhamTyagi** [comment]
As so many trivia answer app are in market. Users uses these app(including Loko hack:grinning:) for cheating in games. Loco developer disabled the accessibility support for their app.
