### ISSUE TITLE
Suggestion for search result

### ISSUE THREAD

**Issue by chanx74** [SubhamTyagi/loco-answers#93]
Questions related to history civics esp. "Name the first/latest ____ of (some country)" the wiki search should start rather than the simple search so for next release try to force the search algo to give a wiki search

Another one is the 9th and/or 10th question on qurekaaaa
"which of these (states/authors/sports person/monuments...) are incorrectly paired with their(places/book title/sport/established by)"

Such question is a guarantee to be a hit and miss. So a suggestion would be a 3rd kind of "pairing search" where only these questions are being made to search.

Also for OCR (if it is being developed) don't use tesseract or any ocr api that requires Google api. 

Couldn't find a thread to post suggestions so posted here 

Request to start a xda thread for this...

**Comment by SubhamTyagi** [comment]
@chanx74 see pair search implementation [here](https://github.com/SubhamTyagi/loco-answers/blob/8dd8dffc030c74828cf1c858438e1b79f3cbc7a6/app/src/main/java/ai/loko/hk/ui/answers/Engine.java#L32)

or you can suggest me proper code impementation for pair search
