### ISSUE TITLE
Support or payment problem

### ISSUE THREAD

**Issue by sudhir1803** [SubhamTyagi/loco-answers#95]
Dear shubham,
I want to support you but your PayPal page payment is not accepting the money it says     
 
This recipient accepts PayPal payments only through their website. To complete this payment, please go to their website and follow their instructions, or email the recipient for instructions.
So in order to support you please update your payment method or accept paytm.

**Comment by kats08** [comment]
Even I want to support you for the wonderful effort by you but unable to do so.

**Comment by selenamariogomez** [comment]
Friends anyone use weshow app ?? Loko app works ???

**Comment by meuserhere** [comment]
No, it doesn't work on Weshow
