### ISSUE TITLE
for all User

### ISSUE THREAD

**Issue by meuserhere** [SubhamTyagi/loco-answers#98]
The developer really worked very hard. To improve its performance in future, please support him by paying a small amount of cash you earned through this app. 
And sadly i unable to pay, please change the payment method in some easy way. Thanks!

**Comment by ronymandal** [comment]
I am only using paytm but here is not accepted paytm

**Comment by royalchauhan** [comment]
Your are right bro we should support the developer but as you through trivia apps we earn paytm money therefore we can only support him by paytm but sadly until now there is no option for that. I really respect the developer fir giving such a useful app for free if he could want to earn money like trivia helper he could sent the app to playstore for high price. But he is different and we really want to support him.

**Comment by ronymandal** [comment]
Ya u r right

**Comment by hackthon2018** [comment]
Is Loko hack new version is  working or not ??
Plz anyone tell..

**Comment by ronymandal** [comment]
It works

**Comment by hackthon2018** [comment]
How @ronymandal

**Comment by hackthon2018** [comment]
On WiFi or mobile data

**Comment by ronymandal** [comment]
I am using mobile data , but sometimes it show blank overlay so that tap many times on get answer, sometimes it show answer 10 sec

**Comment by ronymandal** [comment]
I luv this app

**Comment by hackthon2018** [comment]
Which version of qureka u are using

**Comment by ronymandal** [comment]
Latest version

**Comment by ronymandal** [comment]
Why??

**Comment by hackthon2018** [comment]
If not ok
Tell me the answer

**Comment by ronymandal** [comment]
ronymandal822@gmail.com

**Comment by meuserhere** [comment]
From yesterday, it is giving maximum wrong answer.... Is there anyone facing the same issue? And you are right #ronymandal, sometime have to tap many times to get answer

**Comment by hackthon2018** [comment]
Is Loko hack working properly

**Comment by ronymandal** [comment]
Yaa
