### ISSUE TITLE
Bro the 1.7.0 was but after every update your app is getting more and more bugs . please try to remove bugs and bring a stable version. We really want to support you but we can only do that by paytm please give your paytm no. And bring stable version with OCR . thank you .

### ISSUE THREAD

**Issue by royalchauhan** [SubhamTyagi/loco-answers#99]

**Comment by sumitsinhaa** [comment]
Bro mera naam Sumit hai Yeh To Kehne ki jarurat nahi hai ki aap sabse best developer Ho and ek request aur hai Ek app aur hai Jisko aap uske andar add kar sakte ho ( Q Live ) trivia game pound main paise provide karti hai please help @SubhamTyagi  
https://github.com/SubhamTyagi
